#!/usr/bin/env python3
r"""
chiral_prime_powers.py -- is there a 2-transitive Oliver group inside A_c at a
prime power c = p^a with c = 1 (mod 4)?

WHY THIS EXISTS.  `chiral-graph-properties.md` Theorem 2 read delta_chi = 1/2 at
every prime power c = 1 (mod 4), on the argument that AGL(1,c)'s full twist is an
odd permutation and the index-2 twist is not 2-homogeneous.  That argument is
complete at c PRIME, where a solvable transitive group of prime degree is
confined to AGL(1,p).  At a >= 2 there is no such confinement: the block carries
SEMILINEAR elements too, and a subgroup of GammaL(1,c) can be 2-transitive, even
and Oliver at once where no linear subgroup is.  This script decides which.

WHAT IT SEARCHES.  Subgroups H <= GammaL(1,c) generated by two EVEN elements,
transitive on F_c^*, admitting an Oliver chain (a cyclic normal subgroup with
q-group quotient).  Then Gamma = F_c : H is 2-transitive, inside A_c, and Oliver.

WHAT IT DOES NOT SEARCH.  Affine 2-transitive groups whose stabiliser is NOT of
GammaL(1) type -- the exceptional solvable ones at degrees 9, 25, 49, 121.  Note
the c = 9 group found here IS one of those in the usual classification (3^2:Q8),
reached because Q8 <= GammaL(1,9); the others are not reachable this way.  So a
"none" result is evidence and not a proof.

RESULT (as run):  found at c = 9, 49, 81, 121;  none at c = 25, 169.
The apparent pattern is p = 3 (mod 4) with a even.  At c = 25 the natural
candidate zeta*Frob has order 8 acting in three 8-cycles, hence odd.

The second half of the file re-derives the c = 9 case explicitly and
independently: it builds Gamma = F_9 : <zeta^2, zeta*Frob> as permutations,
checks every generator is even, and computes the orbitals on pairs directly.
Expected output: signs all +1, |Gamma| = 72, one orbital of size 36 = C(9,2).
"""
import itertools, sys
from math import gcd
def gf(p,a):
    # find irreducible poly & build field as ints 0..c-1 via a primitive element table
    c=p**a
    if a==1:
        elems=list(range(c)); mul=lambda x,y:(x*y)%p; add=lambda x,y:(x+y)%p
        # primitive root
        g=next(g for g in range(2,p) if all(pow(g,(p-1)//q,p)!=1 for q in set(f for f in range(2,p) if (p-1)%f==0 and all(f%r for r in range(2,f)))))
        return c,add,mul,g
    # brute search irreducible monic poly of degree a over F_p with primitive root x
    import itertools
    for coeffs in itertools.product(range(p),repeat=a):
        # poly x^a + coeffs[a-1] x^{a-1}+...+coeffs[0]
        def pmul(u,v):
            r=[0]*(2*a-1)
            for i,ui in enumerate(u):
                for j,vj in enumerate(v): r[i+j]=(r[i+j]+ui*vj)%p
            for k in range(2*a-2,a-1,-1):
                if r[k]:
                    for i in range(a): r[k-a+i]=(r[k-a+i]-r[k]*coeffs[i])%p
                    r[k]=0
            return tuple(r[:a])
        x=tuple([0,1]+[0]*(a-2)); one=tuple([1]+[0]*(a-1))
        cur=one; seen=set(); ok=True
        for k in range(c-1):
            if cur in seen: ok=False;break
            seen.add(cur); cur=pmul(cur,x)
        if ok and len(seen)==c-1 and cur==one:
            idx={v:i for i,v in enumerate(itertools.product(range(p),repeat=a))}
            vecs=list(itertools.product(range(p),repeat=a))
            add=lambda u,v: idx[tuple((ui+vi)%p for ui,vi in zip(vecs[u],vecs[v]))]
            mul=lambda u,v: idx[pmul(vecs[u],vecs[v])]
            g=idx[x]
            return c,add,mul,g
def sign(perm):
    n=len(perm); seen=[False]*n; s=1
    for i in range(n):
        if not seen[i]:
            j=i;L=0
            while not seen[j]: seen[j]=True; j=perm[j]; L+=1
            if L%2==0: s=-s
    return s
def closure(gens,n):
    G={tuple(range(n))}; frontier=list(G)
    while frontier:
        nf=[]
        for g in frontier:
            for h in gens:
                x=tuple(h[g[i]] for i in range(n))
                if x not in G: G.add(x); nf.append(x)
        frontier=nf
    return G
def analyse(p,a):
    c,add,mul,g=gf(p,a)
    zero=0 if a==1 else 0
    # elements as ints; multiplicative: powers of g
    pw=[1 if a==1 else next(i for i in range(c) if i==1 or True)]  # placeholder
    # build power table
    one = 1 if a==1 else [i for i in range(c) if all(mul(i,j)==j for j in range(c))][0]
    powers=[one]
    for k in range(c-2): powers.append(mul(powers[-1],g))
    log={v:i for i,v in enumerate(powers)}
    m=c-1
    def mult_perm(k): # x -> g^k x
        return tuple(0 if x==0 else powers[(log[x]+k)%m] for x in range(c))
    def frob_perm(e): # x -> x^{p^e}
        return tuple(0 if x==0 else powers[(log[x]*p**e)%m] for x in range(c))
    def compose(f,h): return tuple(f[h[i]] for i in range(c))
    Z=[mult_perm(k) for k in range(m)]
    Fr=[frob_perm(e) for e in range(a)]
    GL=set()
    for z in Z:
        for f in Fr: GL.add(compose(z,f))
    GL=list(GL)
    even=[h for h in GL if sign(h)==1]
    found=[]
    # search 2-generated subgroups of the even part
    tried=set()
    for h1 in even:
        for h2 in even:
            H=frozenset(closure([h1,h2],c))
            if H in tried: continue
            tried.add(H)
            if len(H)<m: continue
            # transitive on nonzero?
            orb={1}
            fr=[one]; orbs={one}
            for x in list(orbs):
                pass
            reach={one}; st=[one]
            while st:
                x=st.pop()
                for h in (h1,h2):
                    y=h[x]
                    if y not in reach: reach.add(y); st.append(y)
            if len(reach)!=m: continue
            # Oliver: exists cyclic normal N (subgroup of multipliers ∩ H, or any cyclic normal) with H/N a q-group
            Hl=list(H)
            # cyclic subgroups of H
            def order(h):
                k=1;x=h
                while x!=tuple(range(c)): x=compose(x,h);k+=1
                return k
            ok=False
            for h in Hl:
                N=frozenset(closure([h],c))
                # normal?
                if all(compose(compose(x,n),tuple(sorted(range(c),key=lambda i:x[i]))) in N for x in Hl for n in N):
                    q=len(H)//len(N)
                    pr=[f for f in range(2,q+1) if q%f==0]
                    if q==1 or len(set(f for f in pr if all(f%r for r in range(2,f))))==1:
                        ok=True;break
            if ok: found.append((len(H),h1,h2)); break
        if found: break
    print(f"c={c}: {'FOUND 2-transitive Oliver group in A_c, |H|='+str(found[0][0]) if found else 'none'}")
for p,a in [(3,2),(5,2),(7,2),(3,4),(11,2),(13,2)]:
    analyse(p,a)

# explicit independent check at c = 9: Γ = <translations, x->ζ²x, x->ζx³>, orbitals on pairs and signs
def explicit9():
    c,add,mul,g=gf(3,2)
    one=[i for i in range(c) if all(mul(i,j)==j for j in range(c))][0]
    powers=[one]
    for k in range(7): powers.append(mul(powers[-1],g))
    log={v:i for i,v in enumerate(powers)}
    z2=tuple(0 if x==0 else powers[(log[x]+2)%8] for x in range(c))
    zf=tuple(0 if x==0 else powers[(log[x]*3+1)%8] for x in range(c))
    trans=[tuple(add(x,t) for x in range(c)) for t in range(c)]
    gens=[z2,zf]+trans
    print("signs", [sign(h) for h in gens])
    G=closure(gens,c); print("|Γ| =",len(G))
    pairs=[(i,j) for i in range(c) for j in range(i+1,c)]
    seen=set(); sizes=[]
    for pr in pairs:
        if pr in seen: continue
        orb={pr}; st=[pr]
        while st:
            (i,j)=st.pop()
            for h in gens:
                q=tuple(sorted((h[i],h[j])))
                if q not in orb: orb.add(q); st.append(q)
        seen|=orb; sizes.append(len(orb))
    print("orbitals on pairs:",sizes)
explicit9()
