#!/usr/bin/env python3
"""Orbit complexes of A_5: vertex set A_5/K, candidate faces = A_5-orbits of
H-orbits (H a subgroup, acting on A_5/K).  Lutz's 30-vertex Z-acyclic complex is
the orbit complex on A_5/C_2 generated by the D_10-, A_4- and S_3-orbit types.
Enumerate all face-orbit types per K; report them; then search unions."""
import itertools, sys, time
from collections import defaultdict
from lutzA import L, autgroup, closure_group, N
gens,_=autgroup(); G=closure_group(gens)          # A_5 on 30 points, as tuples
ident=tuple(range(N))
def mul(a,b): return tuple(a[b[i]] for i in range(N))
def inv(a):
    r=[0]*N
    for i,x in enumerate(a): r[x]=i
    return tuple(r)
def order(a):
    k,o=a,1
    while k!=ident: k=mul(a,k); o+=1
    return o
# all subgroups of A5 (as sets of elements) up to conjugacy, by closing pairs
def gen_sub(gs):
    S={ident}; fr=[ident]
    while fr:
        nf=[]
        for g in fr:
            for h in gs:
                k=mul(h,g)
                if k not in S: S.add(k); nf.append(k)
        fr=nf
    return frozenset(S)
subs={}
for a in G:
    for b in G:
        H=gen_sub([a,b])
        subs.setdefault(len(H),set()).add(H)
allsubs=[H for k in sorted(subs) for H in subs[k]]
print("subgroups by order:",{k:len(v) for k,v in sorted(subs.items())})
# transitive A5-sets G/K: realise as the orbit of the coset space; we represent
# points of G/K by the K-orbit partition on the regular set?  Simpler: act on
# G itself (regular, 60 points) and quotient by K: point = left coset gK.
Glist=G; gidx={g:i for i,g in enumerate(Glist)}
def coset_space(K):
    Kl=sorted(K, key=lambda g:gidx[g])
    cos={}; pts=[]
    for g in Glist:
        c=frozenset(mul(g,k) for k in K)
        if c not in cos: cos[c]=len(pts); pts.append(c)
    # action of x in G on cosets: x*(gK) = (xg)K
    act={x: tuple(cos[frozenset(mul(x,g) for g in c)] for c in pts) for x in Glist}
    return pts, act
def face_orbit_types(K):
    pts,act=coset_space(K); n=len(pts)
    types={}
    for H in allsubs:
        if len(H)==60 or len(H)==1: continue
        for p in range(n):
            f=frozenset(act[h][p] for h in H)
            if len(f)<=1 or len(f)==n: continue
            orb=frozenset(frozenset(act[x][v] for v in f) for x in Glist)
            types.setdefault(orb, (len(H), len(f), len(orb)))
    return n, act, types
if __name__=="__main__":
    for K in sorted(allsubs, key=len):
        if len(K)==60: continue
        n,act,types=face_orbit_types(K)
        summ=defaultdict(int)
        for orb,(h,fl,ol) in types.items(): summ[(h,fl,ol)]+=1
        print(f"\nK order {len(K)}: |G/K| = {n}; {len(types)} face-orbit types  [(|H|, face size, orbit size): count]")
        print("  ", dict(sorted(summ.items())))
