#!/usr/bin/env python3
import itertools, sys, time
from collections import defaultdict
import orbitcx as O
def closure_masks(face_orbits):
    """faces (as bitmasks) of the complex generated by these orbits of facets"""
    F=set()
    for orb in face_orbits:
        for f in orb:
            m=0
            for v in f: m|=1<<v
            sub=m
            while True:
                F.add(sub)
                if sub==0: break
                sub=(sub-1)&m
    F.discard(0)
    return F
def chi(F): return sum((-1)**(bin(f).count('1')-1) for f in F)
def chi_link(F,v=0):
    return sum((-1)**(bin(f).count('1')-2) for f in F if (f>>v&1) and bin(f).count('1')>=2)
def betti_mod(F,n,p):
    by=defaultdict(list)
    for f in F: by[bin(f).count('1')-1].append(f)
    idx={d:{f:i for i,f in enumerate(sorted(v))} for d,v in by.items()}
    top=max(by)
    def rank(d):
        rows=idx.get(d-1,{}); cols=sorted(by[d])
        if not rows or not cols: return 0
        M=[[0]*len(rows) for _ in cols]
        for j,f in enumerate(cols):
            bits=[i for i in range(n) if f>>i&1]
            for k,b in enumerate(bits):
                g=f&~(1<<b)
                if g in rows: M[j][rows[g]]=(-1)**k%p
        r=0; nc=len(rows)
        for c in range(nc):
            piv=next((i for i in range(r,len(M)) if M[i][c]%p),None)
            if piv is None: continue
            M[r],M[piv]=M[piv],M[r]; iv=pow(M[r][c],-1,p); M[r]=[(x*iv)%p for x in M[r]]
            for i in range(len(M)):
                if i!=r and M[i][c]%p:
                    fct=M[i][c]; M[i]=[(a-fct*b)%p for a,b in zip(M[i],M[r])]
            r+=1
        return r
    rk={d:rank(d) for d in range(1,top+1)}
    out=[]
    for d in range(top+1):
        nd=len(by[d]); ker=nd-rk.get(d,0) if d>=1 else nd
        out.append(ker-rk.get(d+1,0)-(1 if d==0 else 0))
    return out
def nonevasive(F,n,deadline):
    memo={}
    def verts(S): 
        m=0
        for f in S: m|=f
        return m
    def NE(S):
        S=frozenset(S)
        if S in memo: return memo[S]
        if time.time()>deadline: raise TimeoutError
        vm=verts(S); nv=bin(vm).count('1')
        if nv==1: return True
        if not S: return False
        if chi(S)!=1: memo[S]=False; return False
        res=False
        vs=[i for i in range(n) if vm>>i&1]
        for v in vs:
            lk={f&~(1<<v) for f in S if (f>>v&1) and f!=(1<<v)}
            if not lk: continue
            dl={f for f in S if not (f>>v&1)}
            if NE(lk) and NE(dl): res=True; break
        memo[S]=res; return res
    return NE(F)
def run(Korder, maxk, limit):
    K=next(H for H in O.allsubs if len(H)==Korder)
    n,act,types=O.face_orbit_types(K)
    T=list(types.keys()); t0=time.time()
    full=(1<<n)-1
    stats=defaultdict(int); survivors=[]
    for k in range(1,maxk+1):
        for combo in itertools.combinations(range(len(T)),k):
            if time.time()-t0>limit: print("  time limit"); break
            orbs=[T[i] for i in combo]
            # skip if some orbit is contained in another's closure (not a generator set)
            F=closure_masks(orbs)
            if full in F: continue
            stats['tried']+=1
            if chi(F)!=1: continue
            stats['chi1']+=1
            if chi_link(F)!=1: continue
            stats['link1']+=1
            b2=betti_mod(F,n,2)
            if any(b2): stats['F2fail']+=1; continue
            b3=betti_mod(F,n,3); b5=betti_mod(F,n,5)
            if any(b3) or any(b5): stats['F35fail']+=1; continue
            stats['acyclic_mod235']+=1
            desc=[(types[o][0],types[o][1],types[o][2]) for o in orbs]
            try:
                ne=nonevasive(F,n,time.time()+30)
                stats['NE' if ne else 'evasive']+=1
                print(f"  |G/K|={n} types {desc}: {len(F)} faces, acyclic mod 2,3,5 -> {'NONEVASIVE <== COUNTEREXAMPLE' if ne else 'EVASIVE'}")
                if ne: survivors.append((n,desc))
            except TimeoutError:
                stats['NE_timeout']+=1
                print(f"  |G/K|={n} types {desc}: {len(F)} faces, acyclic mod 2,3,5 -> NE recursion TIMEOUT")
                survivors.append((n,desc,'timeout'))
    print(f"|G/K|={n}, up to {maxk} types: {dict(stats)}  ({time.time()-t0:.0f}s)")
    return survivors
if __name__=="__main__":
    Korder=int(sys.argv[1]); maxk=int(sys.argv[2]); limit=float(sys.argv[3])
    run(Korder,maxk,limit)
