# The construction, at general degree 2p: p blocks of 2, the index-2 subgroup of
# (C_2)^p generated by EVEN products of the p transpositions, extended by a
# p-cycle permuting the blocks diagonally.
def build(p):
    n=2*p
    def comp(a,b): return tuple(a[b[i]] for i in range(n))
    def perm(cycles):
        q=list(range(n))
        for c in cycles:
            for i in range(len(c)): q[c[i]]=c[(i+1)%len(c)]
        return tuple(q)
    def sign(q):
        seen=[False]*n; s=1
        for i in range(n):
            if seen[i]: continue
            l=0; j=i
            while not seen[j]: seen[j]=True; j=q[j]; l+=1
            if l%2==0: s=-s
        return s
    t=[perm([[2*i,2*i+1]]) for i in range(p)]
    cp=perm([[2*i for i in range(p)],[2*i+1 for i in range(p)]])
    gens=[comp(t[i],t[i+1]) for i in range(p-1)]+[cp]
    G={tuple(range(n))}; fr=[tuple(range(n))]
    while fr:
        new=[]
        for x in fr:
            for g in gens:
                y=comp(g,x)
                if y not in G: G.add(y); new.append(y)
        fr=new
    orb={0}; ch=True
    while ch:
        ch=False
        for g in G:
            for x in list(orb):
                if g[x] not in orb: orb.add(g[x]); ch=True
    return len(G), all(sign(g)==1 for g in G), len(orb)==n
for p in [2,3,5,7,11]:
    o,even,tr = build(p)
    print("degree %2d: |G| = %-6d = 2^%d * %d ; inside A_n: %s ; transitive: %s"
          % (2*p, o, (p-1), p, even, tr))
